name: Java Weather Service CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run Unit Tests
        run: ./gradlew test

      - name: Run Integration Tests
        run: ./gradlew integrationTest

      - name: Run Cucumber Tests
        run: ./gradlew cucumberTest

      - name: Build Docker image
        run: |
          docker build -t weather-service:latest .

      - name: Run Load Tests
        run: ./gradlew gatlingRun

      - name: Save test results
        uses: actions/upload-artifact@v2
        with:
          name: test-results
          path: |
            build/reports/tests/
            build/reports/cucumber/
            build/reports/gatling/

  deploy:
    needs: build
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build with Gradle
        run: ./gradlew build -x test

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: your-registry/weather-service:latest

    # Add deployment steps to your environment (e.g., AWS, Azure, GCP)
    # - name: Deploy to production
    #   run: ./deploy-to-production.sh